### ISSUE TITLE
Not an issue, a question

### ISSUE THREAD

**Issue by AlbertoMCS** [yakitoritabetai/Leaflet.LabelTextCollision#9]
How do you create the cool style of the label (blue with outline white). Cannot see any css anywhere.
![image](https://user-images.githubusercontent.com/16774169/220773010-f72911fc-ea71-452b-b2ae-7d54e2bee01a.png)

**Comment by yakitoritabetai** [comment]
Thank you for your question.
It's javascript, not css. Implemented with fillText() and strokeText() for Canvas.
This URL has the target source.
https://github.com/yakitoritabetai/Leaflet.LabelTextCollision/blob/f99efa318f49a88bca7ce19ee63e8b792a29c63c/dist/L.LabelTextCollision.js#L179-L190
